### ISSUE TITLE
 Could not find a version that satisfies the requirement fdts

### ISSUE THREAD

**Issue by ahmadxon** [ZhaoqingLiu/FuzzyTrees#1]
While installation this error accrues.
$pip install fdts

ERROR: Could not find a version that satisfies the requirement fdts
ERROR: No matching distrib
![error](https://user-images.githubusercontent.com/5636506/137137500-cdb91203-911e-4253-a4ad-4151463c4433.PNG)
ution found for fdts

**Comment by ahmadxon** [comment]
this source is for which python version?

**Comment by ZhaoqingLiu** [comment]
Waiting process
